// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Content: typeof import('./../src/components/content/Index.vue')['default']
    ContentTabContextMenu: typeof import('./../src/components/content/tabContextMenu.vue')['default']
    ContentTablist: typeof import('./../src/components/content/tablist.vue')['default']
    ContentWelcome: typeof import('./../src/components/content/Welcome.vue')['default']
    Editor: typeof import('./../src/components/Editor.vue')['default']
    Editorcopy: typeof import('./../src/components/Editorcopy.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    Layout: typeof import('./../src/components/Layout.vue')['default']
    Left: typeof import('./../src/components/left/Index.vue')['default']
    LeftActivitybar: typeof import('./../src/components/left/Activitybar.vue')['default']
    LeftSidebar: typeof import('./../src/components/left/Sidebar.vue')['default']
    LeftWelcome: typeof import('./../src/components/left/Welcome.vue')['default']
    Main: typeof import('./../src/components/Main.vue')['default']
    Resize: typeof import('./../src/components/Resize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
