// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./../src/components/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Header: typeof import('./../src/components/Header.vue')['default']
    Layout: typeof import('./../src/components/Layout.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Main: typeof import('./../src/components/Main.vue')['default']
    Nav: typeof import('./../src/components/Nav.vue')['default']
  }
}

export { }
